### ISSUE TITLE
Setting default subfolder for clipped notes

### ISSUE THREAD

**Issue by aviskase** [qownnotes/web-companion#12]
Hi,

Is there a way to set default subfolder to put notes created by web-companion (e.g. Inbox)? Right now notes are added to whatever subfolder was selected in the app

Thanks.

**Comment by pbek** [comment]
This question would more belong to https://github.com/pbek/QOwnNotes/issues.

It's hard to handle sub-folders there, because they also would need to be created if they are gone. Or maybe one note folder has sub-folders turned off at all... 

see
https://github.com/pbek/QOwnNotes/blob/3e2f83a9ebe1f8be05fad7472367ea5918cc61d4/src/services/websocketserverservice.cpp#L221

the note is fetched (if existing) in https://github.com/pbek/QOwnNotes/blob/53a9d29f6f340a2d11214339e1e6430c534f47ff/src/entities/note.cpp#L412
