### ISSUE TITLE
FR: Do not change the opened notebook

### ISSUE THREAD

**Issue by gerroon** [qownnotes/web-companion#27]
Hi

This is a feature request so I am not putting down all that info in the template.

I like the ability to select the notebook which I will send the bookmarks to but changing the notebook in the bookmark adding window also changes the opened notebook in Qownnotes. Is it possible to have an option for user to define that behavior? 

I personally do not like the opened notebook to change to the one in the bookmark dialog everytime I am adding a new bookmark. I use different notebooks for different stuff and different types of bookmarks file.

thanks

**Comment by pbek** [comment]
That would be very, very hacky, since QOwnNotes has no concept of notes outside the open note folder. If you really need such a think you could open two instances of QOwnNotes (in two different sessions, see https://www.qownnotes.org/getting-started/cli-parameters.html) and use two different server socket ports (*Browser extension* settings). The you can tell the browser extension to talk to the 2nd QOwnNotes instance (you could leave that instance in the tray only).

**Comment by gerroon** [comment]
Hi

Thanks for the reply. I would need many opened Qownnotes, since I have many notebooks that gets data from the browser.

I ll keep this as a feature request maybe someone who can develop this can implement it in the future.

**Comment by pbek** [comment]
I doubt that this will ever be implemented, since it goes against the fundamentals of QOwnNotes. 😁

**Comment by pbek** [comment]
I guess I can close this.
